python3 -m src.main \
        --image_dir /opt/data/ARGON/iu_xray/images/ \
        --ann_path /opt/data/ARGON/iu_xray/new_annotation.json \
        --ann_path_tokenizer /opt/data/ARGON/iu_xray/new_annotation.json \
        --vocab_path /opt/data/ARGON/iu_xray/vocab.pickle \
        --dataset_name iu_xray \
        --src_max_seq_length 60 \
        --threshold 3 \
        --batch_size 16 \
        --epochs 100 \
        --save_dir /opt/data/ARGON/results/iu_xray \
        --record_dir /opt/data/ARGON/results/iu_xray \
        --step_size 50 \
        --gamma 0.1 \
        --report_mode report \
        --seed 9223 \
        --n_gpu 2 \
